[package]
name = "amethyst_network"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepromain@gmail.com>", "Lucio Franco (LucioFranco) <luciofranco14@gmail.com>"]
description = "Amethyst network crate"
keywords = ["networking", "specs", "ecs", "amethyst", "serialization"]
categories = ["game-engines"]

documentation = "https://www.amethyst.rs/doc/master/doc/amethyst_network/index.html"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"
license = "MIT/Apache-2.0"

[features]
profiler = [ "thread_profiler/thread_profiler" ]
nightly = [ "amethyst_core/nightly" ]

[dependencies]
amethyst_core = { path = "../amethyst_core", version = "0.3" }
serde = { version = "1.0.16", features = ["serde_derive"] }
shrev = "1.0"
shred = "0.5"
bincode = "0.9.2"
log = "0.4"
uuid = { version = "0.5.1", features = ["v4","serde"] }
thread_profiler = { version = "0.1" , optional = true }
fern = "0.5"
mio = "0.6.16"
byteorder = "1.2.6"
itertools = "0.7.8"